# Generated by Django 2.2.3 on 2019-11-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Post Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('is_authenticated', models.BooleanField(verbose_name='Is Authenticated')),
            ],
        ),
    ]
