# Generated by Django 2.2.3 on 2020-02-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='liked',
        ),
    ]
