# Generated by Django 2.2.3 on 2019-11-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='name',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.CharField(default='Image1', max_length=10, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='posts',
            name='place',
            field=models.CharField(default='Place1', max_length=10, verbose_name='Place'),
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='title', max_length=10, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.CharField(default='Description', max_length=100, verbose_name='Description'),
        ),
    ]
