# Generated by Django 2.2.3 on 2019-11-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_settings_user_id'),
        ('posts', '0003_auto_20191103_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='setting_id',
            field=models.ForeignKey(null=True, on_delete='Settings', to='settings.Settings'),
        ),
    ]
