# Generated by Django 2.2.7 on 2019-11-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191104_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='place',
            field=models.CharField(default='Place1', max_length=20, null=True, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='setting_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Settings'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(default='title', max_length=25, null=True, verbose_name='Title'),
        ),
    ]
