# Generated by Django 2.2.7 on 2019-11-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191111_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='created',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='updated',
        ),
    ]
