# Generated by Django 2.2.7 on 2019-11-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191111_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='body',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='setting_id',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='status',
        ),
    ]
