# Generated by Django 2.2.7 on 2019-11-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20191111_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=1, upload_to='post_images'),
            preserve_default=False,
        ),
    ]
