# Generated by Django 2.2.9 on 2020-01-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='city',
            field=models.CharField(default='Delhi', max_length=20, verbose_name='City'),
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Description', max_length=100, null=True, verbose_name='Description')),
                ('place', models.CharField(default='Journey to The End of the World...', max_length=20, null=True, verbose_name='Place')),
                ('image', models.ImageField(upload_to='post_images')),
                ('post_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent_places', to='posts.Posts')),
            ],
            options={
                'ordering': ('-place',),
            },
        ),
    ]
