# Generated by Django 2.2.9 on 2020-01-31 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200125_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='posts.Posts'),
        ),
    ]
