# Generated by Django 2.2.3 on 2020-02-02 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200131_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.today, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(max_length=264, null=True, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(default='Description', max_length=100, null=True, verbose_name='Description'),
        ),
    ]
