# Generated by Django 2.2.3 on 2019-11-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='Location')),
                ('bio', models.CharField(max_length=100, null=True, verbose_name='Bio')),
                ('interests', models.CharField(max_length=100, null=True, verbose_name='Interests')),
            ],
        ),
    ]
