# Generated by Django 2.2.3 on 2020-02-03 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='Location')),
                ('bio', models.CharField(max_length=100, null=True, verbose_name='Bio')),
                ('interests', models.CharField(max_length=100, null=True, verbose_name='Interests')),
                ('followers', models.IntegerField(default=0, verbose_name='Followers')),
                ('no_of_posts', models.IntegerField(default=0, verbose_name='No of Posts')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
