# Generated by Django 2.2.3 on 2020-02-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
    ]
