# Generated by Django 2.2.3 on 2020-02-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_total_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_posts',
        ),
    ]
